name: Backend Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: production
      working-directory: back-end

    - name: Build backend app
      run: npm run build
      working-directory: back-end

    - name: Start backend app
      run: npm start
      working-directory: back-end

    - name: Run backend tests
      run: npm run test
      working-directory: back-end   