name: Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './back-end'

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    - name: Use Node.js 18.x for BACKEND
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './back-end/package-lock.json'
    - name: Installing dependencies
      working-directory: './back-end'
      run: npm install
    - name: Generating coverage information
      run: npm run coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}//server/coverage/lcov.info
        base-path: ./back-end/